### ISSUE TITLE
Caption mis-positioned with Boostrap4

### ISSUE THREAD

**Issue by zeroasterisk** [airbnb/react-dates#100]
![ss](https://puu.sh/rrpJ6/d495232dff.png)

```scss
/* TEMP FIX */
.CalendarMonth {
  table {
    caption: {
      caption-side: top;
    }
  }
}
.CalendarMonth__caption {
  caption-side: top;
}
```
