### ISSUE TITLE
Navigation arrows not showing up

### ISSUE THREAD

**Issue by cacpmw** [airbnb/react-dates#2109]
**react-dates version**
"react-dates": "^21.8.0",

**Describe the bug**
Navigation arrows are not showing up on calendar

**Source code (including props configuration)**
```JS
//SingleDatePickerWrapper.jsx
import React from 'react';

import { SingleDatePicker } from 'react-dates';

export default function SingleDatePickerWrapper(props) {

    return (
        <SingleDatePicker
            id="date_input"
           {...props}
        />
    );
}
```
```JS
//App.js
import React from 'react';
import SingleDatePickerWrapper from "./components/SingleDatePickerWrapper.jsx";
import 'react-dates/lib/css/_datepicker.css';
import './App.css';


<SingleDatePickerWrapper
          date={this.state.birthday} 
          onDateChange={date => this.setState({ birthday: date })}
          focused={this.state.focused}
          onFocusChange={({ focused }) => this.setState({ focused })} 
          numberOfMonths={1}
          withPortal={true}
          isOutsideRange={(date) => date.isAfter()}
          readOnly={true}
          required={true}
          screenReaderInputMessage="Please select a birthday"
          hideKeyboardShortcutsPanel={true}
        />

```
```JS
//index.js
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import 'react-dates/initialize';

import { App } from './App';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render((
  <App />
), document.getElementById('root'));
registerServiceWorker();

```

```CSS
/*This css is inject into the App.css*/
.DateInput_fang {
    -webkit-transform: translateY(1px);
    -ms-transform: translateY(1px);
    transform: translateY(1px);
}

input.DateInput_input::placeholder {
    color: '#3D3D3D';
    font-weight: 500;
}

input.DateInput_input:-ms-input-placeholder {
    color: #3D3D3D;
}

input.DateInput_input::-webkit-input-placeholder {
    /* Edge */
    color: '#3D3D3D';
    font-weight: 500;
}

input.DateInput_input:-moz-placeholder {
    color: #3D3D3D;
}
td.CalendarDay__selected, .CalendarDay__selected:active, .CalendarDay__selected:hover {
    background: #00a699;
    border: 1px solid #602c9d;
    color: #fff;
}
button.DayPickerKeyboardShortcuts_show__bottomRight {
    border-top: 26px solid transparent;
    border-right: 33px solid #602c9d;
    bottom: 0;
    right: 0;
}
```

**Screenshots/Gifs**
![image](https://user-images.githubusercontent.com/7819913/116705326-c895f900-a9a2-11eb-87de-1e6b3d37b565.png)
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Edge Version 90.0.818.49 (Official build) (64-bit) || Chrome Version 90.0.818.49 (Official build) (64-bit)

**Additional context**
I even tried the default SDP and it still doesnt show the arrows
