### ISSUE TITLE
SingleDatePicker misaligned

### ISSUE THREAD

**Issue by brunocoelho** [airbnb/react-dates#248]
I don't why a left property is being applied to my calendar.

**Comment by majapw** [comment]
Can you share the props you're passing down to the `SingleDatePicker`?

**Comment by majapw** [comment]
Can you also log what `window.innerWidth` is calculated as in your console? Are you using iframes or anything similar that might change this value?

**Comment by brunocoelho** [comment]
That's what I'm passing down.

```jsx
<SingleDatePicker
   date={this.state.date}
   focused={this.state.focused}
   id="date_input"
   isOutsideRange={() => false}
   numberOfMonths={1}
   placeholder="Date and Time of Death (picker)"
   onDateChange={this.onDateChange}
   onFocusChange={this.onFocusChange}
/>
```

And `window.innerWidth` is 1280.

**Comment by majapw** [comment]
Is `window.innerWidth` still 1280 at the time of `componentDidMount`? Is there a `right` style being applied to the picker at any point?

**Comment by brunocoelho** [comment]
It's always 1280, I never resize the window. Nope, I never add any `right` style.

This is the result when I apply `left:0` to this selector `.SingleDatePicker__picker.SingleDatePicker__picker--show`

![screen shot 2017-01-12 at 8 22 03 pm](https://cloud.githubusercontent.com/assets/827445/21912459/d9ed36f0-d904-11e6-940b-f2419c842249.png)

**Comment by majapw** [comment]
@brunocoelho That makes sense because what I expect the calculated style to be is `left: 0` with your particular set-up.

Basically, on `componentDidMount` (and also whenever you resize the window), the inline styles that are applied get set here: https://github.com/airbnb/react-dates/blob/master/src/components/SingleDatePicker.jsx#L207:L212. 

This is somewhat obfuscated but basically this file (https://github.com/airbnb/react-dates/blob/master/src/utils/getResponsiveContainerStyles.js) ends up setting the `ANCHOR_DIRECTION` value (in this case, `left`) of the picker based on the window width, and the `this.dayPickerContainer.getBoundingClientRect()` `right` value. In your case, for whatever reason the client rect right value is ... larger than the window width. This may have something to do with how you're styling the input to fill the space. 

Can you share 

(a) the value of `document.querySelector('.SingleDatePicker__picker').getBoundingClientRect()`
(b) what styles you are applying to `.DateRangePicker` (or anything else) to get it to fill the width of your container?

Sorry for all the back and forth! I think we're getting closer to a solution (and remote debugging is hard).

**Comment by brunocoelho** [comment]
Hi @majapw I appreciate your attention, you don't need to apologize, remote debugging is pretty hard.

a) 
<img width="783" alt="screen shot 2017-01-13 at 3 33 11 pm" src="https://cloud.githubusercontent.com/assets/827445/21941023/a1357542-d9a5-11e6-98b6-6d8723ef88fa.png">

b) In order to fix the position and add some styling:

```css
.deader .SingleDatePicker {
  display: block;
}

.deader .SingleDatePicker .SingleDatePickerInput {
  border: 1px solid #e5e6e7;
}

.deader .SingleDatePicker .SingleDatePickerInput .DateInput {
  color: #9a9a9a;
  font-size: 14px;
  width: auto;
}

.deader .SingleDatePicker__picker.SingleDatePicker__picker--show {
  left: 0 !important;
}

```
