### ISSUE TITLE
Cannot see blinking cursor when typing into date inputs

### ISSUE THREAD

**Issue by chris-pearce** [airbnb/react-dates#618]
Due to the inputs (`.DateInput__input`) having `opacity: 0;` set:

```css
.DateInput__input {
    opacity: 0;
    position: absolute;
    top: 0;
    left: 0;
    border: 0;
    height: 100%;
    width: 100%;
}
```

You do not see the blinking cursor as you type into the overlaying `<div>` element (`.DateInput__display-text`) making it practically unusable as you cannot see where you're typing.

The heavy handed workaround is to make the inputs `readonly` via the `readOnly` prop, however, disabling a user from being able to enter their own dates hinders the overall UX.
